### ISSUE TITLE
Missing files on the demo page

### ISSUE THREAD

**Issue by stefandevo** [inextdeve/shadcn-country-region-select#1]
Thanks for this component!

Just to let you know that on the demo page https://shadcn-country-region-select.vercel.app/ at the installation instructions the `import { filterCountries } from "@/lib/helpers";` is missing for the country-select.tsx.

**Comment by inextdeve** [comment]
Hi, the `import { filterCountries } from "@/lib/helpers";` line is present, You may not have noticed it !

**Comment by stefandevo** [comment]
Yeah, I know. It's just when you use the snippets to copy/paste in your code you miss the lib/helpers file. So you have to manually look up in the repo to add this file (it's not available as a copy/paste from the https://shadcn-country-region-select.vercel.app/ page.

![CleanShot 2024-08-07 at 10 17 45@2x](https://github.com/user-attachments/assets/3d879303-c753-4e0a-b962-31d2e895502b)
